Feature branch
mcastorena0316/enumerable-methods pull request #2
Opened 2019-11-23 01:04 UTC by mcastorena0316

Hi, i think im ready for my first review. Thanks!

2019-11-23 06:47 UTC, Ispirett requested changes
### Status Changes Required
@mcastorena0316  great work so far :100:  :+1: 
There are  a lot of errors when testing your code :bug: 

##### Errors
- [ ] 
  **ArgumentError:
       wrong number of arguments (given 0, expected 1)**

My_each, my_each_with index, my_select, my_all, my_any, my_none my_count, and my_inject Should all have parameters

- [ ]  ```LocalJumpError:
        no block given (yield)```
My_inject!  You need a guard case, at the top of your function,    return to_enum unless block_given?


**Suggestion**
You  can test your methods against the orignal methods example: array.my_none?(2) == array.none?(2)

2019-11-25 17:07 UTC, mcastorena0316 commented
hi, I follow your suggestions and test my methods against the originals and its currently working. Also I add the guardcase as recommended. Thanks!

2019-11-25 19:18 UTC, whiz25 requested changes
## Hey good job @mcastorena0316 
You have done well in implementing the features for this project. I tested your methods and found they fail against some edge cases. We need to fix those failing cases before we can merge this PR. 
Please look at my comments and make changes accordingly.

### Martin Afani

2019-11-25 19:20 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] when no block or argument is given returns true when none of the collection members are false or nil
- [ ] when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-25 19:21 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] false if none of the collection matches the pattern

2019-11-25 19:22 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-25 19:22 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] returns the number of items in enum through enumeration
- [ ] counts the number of items in enum that are equal to item if an argument is given

2019-11-25 19:23 UTC, whiz25 commented on enumerable.rb
> +end
- [ ] returns an Enumerator if no block is given

2019-11-25 19:23 UTC, whiz25 commented on enumerable.rb
> +  end
- [ ] combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-11-26 20:56 UTC, mcastorena0316 commented
Hi, I did the reccommended changes and try it a bunch of times with different scenarios and variables, lets hope this time its the winner. Thanks!

2019-11-27 04:07 UTC, uche-inyama requested changes
## Changes Required

Hi mcastorena0316

The corrections pointed out  by **```whiz25```** hasn't been implemented correctly; there are still failing the test cases.

Please use the examples in this [document](https://ruby-doc.org/core-2.6.5/Enumerable.html) as a guide while testing out the methods. 

After implementing those changes submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2019-11-27 15:44 UTC, mcastorena0316 commented
Thanks for your review, i found my mistakes and i correct them.

2019-11-27 17:33 UTC, wathigo requested changes
# Change Required  
## Great progress team :clap:  
We only have one issue to address, See the comment :point_down:  
### After implementing the change, submit another request for review.

**Happy Coding :computer: 
Simon Wathigo**

2019-11-27 17:33 UTC, wathigo commented on enumerable.rb
> +    x
**[REQUIRED]**
* combines all elements of enum by applying a binary operation, specified by a block.
```
Failure/Error: let(:search) { proc { |memo, word| memo.length > word.length ? memo : word } }
     
     NoMethodError:
       undefined method `length' for 0:Integer
```

2019-11-27 20:09 UTC, mcastorena0316 commented
Thanks for explaining me the issue,  I believe I fixed it this error and doesn't appear anymore.

:four_leaf_clover: this is a lucky charm for luck to approve my project

2019-11-27 20:17 UTC, imhta requested changes
# Changes Required 🛑 

### Hello @mcastorena0316 , 👋 You have done a good job with this project but still there is a test failling in your `my_inject` method.

see comments for more details

----
### Don't forgot to request for another code review
----

Happy coding,
** Pon Muthu Selvam N**
_If you have any queries, feel free to ping me on slack_

2019-11-27 20:20 UTC, imhta commented on enumerable.rb
> +  end
Your `my_inject` method is failing a test
```bash
  1) enumerables my_inject combines all elements of enum by applying a binary operation, specified by a block
```

2019-11-27 22:37 UTC, mcastorena0316 commented
Thanks, changes made

2019-11-27 22:38 UTC, wathigo approved these changes
# Approved :smile:  
## Great work implementing all the requested changes :+1:  

### You  may move on :next_track_button:  

**Happy Coding :computer: 
Simon Wathigo**

2019-11-27 23:26 UTC, merged